### PR TITLE
Request inclusion of my upgrades and bugfixes to next release (0.17)

### PR DESCRIPTION
**Pull request by jwestra**
Hi!,

I forked the Troilus 0.17-SNAPSHOT to fix some bugs, upgrade to Cassandra 3.x driver APIs which uses TypeCodec and CodecRegistry for serialization/deserialization instead of DataType APIs, and other enhancements, which is required by our company, Kritek, LLC.  I'd like to have my fork upgrades and bug fixes included in the original Troilus project, so my company can stay in-line with your releases and not diverge even further on our own fork.  

I am not clear on the process here, but my understanding is that I make a Pull Request, which needs approval for inclusion.

Here are the items I have added to the Kritek Fork (from the changes.txt).
## 0.17 - Kritek Fork
- Pagination Support - ListRead.withPagingState(), ListReadQuery.toStatementAsync()
- Inheritance of @Field mappings for entities in BeanMapper
- Upgrade from Cassandra Datastax 2.2.0-rc2 driver to 3.0.0-beta1 driver
- Upgrade tests from Cassandra 2.x to Cassandra 3.0.0 (see pom.xml dependency and CassandraDB.java)
- LocalDateTime Support - Record.java interfaces and implementations
- bugfix: WriteQueryDataImpl.java toUpdateStatementAsync() no longer maps primary keys into Update SET
- bugfix: RecordImpl.PropertySourceAdapter rewrote read() and read(String name, Class<?> clazz1, Class<?> clazz2) to work with UDTValue collections.
- New test cases: PaginationTest.java, EntityInheritanceMappingTest.java, UDTValueMappingCollectionTests.java
## POMs

The original poms referenced some dependencies that did not exist in Maven Central.  They were changed as follows in my forked version.

<dependency>
    <groupId>org.reactivestreams</groupId>
    <artifactId>reactive-streams</artifactId>
    <version>1.0.0.final</version>  **changed to 1.0.0**
</dependency>
<dependency>
    <groupId>org.reactivestreams</groupId>
    <artifactId>reactive-streams-tck</artifactId>
    <version>1.0.0.final</version>
    <scope>test</scope>  **changed to 1.0.0**
</dependency>

I also created Maven properties for some of the version, as well, for clarity and reuse.
## Tests

I ran all tests individually from the Eclipse IDE.  They all run 100%.  However, when running from commandline using "mvn test", they fail because the Surefire plugin does not process the JUnit @RunWith annotation properly.
## Logging

I have not included any extra SLF4J logging yet.  However, I believe more logging in Troilus will benefit troubleshooting issues with the framework as well as code calling it.  It was quite time-consuming troubleshooting all the asynchronous, futures calls in the debugger :)  I'd be interested in hearing where your thoughts are on this topic as well.

### CODE REVIEW

**Comment by spodkowinski** [comment]
Hi Jason

Thanks for your PR! I had the chance to look at some of the changes today and noticed a couple of issues:

Some files have been replaced by a version using CRLF instead of LF. This makes it very hard to track the actual changes, see 1f0ef1c0305d274e3ef700738d1766fe11afb693 or 2a3e52a3f0980b484d91227e5526a2790e115c0e for example. Please make sure not to commit files using CRLF by changing your git `core.autocrlf` settings as described [here](http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/).

Classes in `troilus-core-java7` must be usable from Java 7. I'm getting compile errors running maven in this directory using jdk7 (mainly caused by new java.time package).

Style issues: use of mixed tab/space whitespace characters - should be spaces only.

The PR is quite big so it will take some care to merge it in a way that makes sense. What do you think @grro ?

**Comment by jwestra** [comment]
Thanks for your reply Stefan.  I am sorry I did not have all the settings correct.  I will set them up for the future.  Is there a link to your coding standards for Troilus, so I better meet these expectations?

1.) LocalDateTime - we should just remove it from Record interface, impls, junits in all projects.  This would resolve the jdk7.  It is not essential anyway.  The main features causing us to fork were C\* 3.x support, inheritance of @Field, pagination, mapping collections of user-defined types.

2.) Style issues: mixed table/space:  Not sure if this is this an IDE setting or something I just do by-hand.  I will look into it.  Thanks.

**Comment by grro** [comment]
I'm going to take a look into the PR next week. Regarding to the Java7 issue I suggest to thing about removing the Java7 support (after this fix). Supporting Java7 and Java8 in parallel increases the code complexity in a significant way.

**Comment by grro** [comment]
Hi Jason,

I've merged the pull request (I've just removed some comments and dead code. Furthermore I've fixed the Java7 LocalDateTime issue). I'm going to build a new release the next days. It would be great if you have some time to test the current trunk within your environment. 

Gregor

**Comment by jwestra** [comment]
Hi Gregor,

I tested the merged changes and they work fine.  Thank-you!  This is great news.  

Can you send me your contact information to jason@kritek.org?  I'd like to better understand the coding standards to follow to make future Pull Requests easier for you to merge and to just chat about overall usage questions, and roadmap of Troilus in the future?

Jason

**Pull request merged**
